* 微服务开发的12项要素

+ Configuration Service
+ Discovery Service
+ Circuit breakers
+ Distributed sessions


spring cloud官方文档提到的服务开发的12项要素。

I. Codebase
从一个代码库部署到多个环境。
II. Dependencies
使用显式的声明隔离依赖，即模块单独运行，并可以显式管理依赖。
III. Config
在系统外部存储配置信息。
IV. Backing Services
把支持性服务看做是资源，支持性服务包括数据库、消息队列、缓冲服务器等。
V. Build, release, run
严格的划分编译、构建、运行阶段，每个阶段由工具进行管理。
VI. Processes
应用作为无状态执行。
VII. Port binding
经由端口绑定导出服务，优先选择 HTTP API 作为通用的集成框架。
VIII. Concurrency
并发性使用水平扩展实现，对于web就是水平扩展web应用实现。
IX. Disposability
服务可处置性，任何服务可以随意终止或启动。
X. Dev/prod parity
开发和生产环境保持高度一致，一键式部署。
XI. Logs
将日志看做是事件流来管理，所有参与的服务均使用该方式处理日志。
XII. Admin processes
管理任务作为一次性的过程运行（使用脚本管理服务启动和停止）。

* 使用Spring Cloud和Docker构建微服务

用例子来说明，非常方便入门 http://www.kennybastani.com/2015/07/spring-cloud-docker-microservices.html

Configuration Service
Discovery Service
Circuit breakers
Distributed sessions

** 问题： Connect to localhost:2375 [localhost ]

DOCKER_HOST=unix:///var/run/docker.sock mvn clean install
* spring boot
** 介绍

Spring Boot是Spring团队推出的新框架，它所使用的核心技术还是Spring框架，主要是Spring 4.x，所以如果熟悉spring 4的人，能够更快的接受和学会这个框架。Spring boot可以看做是在spring框架基础上再包了一层，这一层包含方便开发者进行配置管理和快速开发的模块，以及提供了一些开箱即用的工具，比如监控等。

** Spring Boot Reference Guide

+ [[http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#getting-started][英文]]
+ [[https://github.com/qibaoguang/Spring-Boot-Reference-Guide][中文]]

** Quick Start：使用spring boot创建一个应用

[[http://projects.spring.io/spring-boot/][参考文章]] 官网

1. 先通过maven新建一个项目

2. 修改配置
#+begin_src xml
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.3.6.RELEASE</version>
  </parent>
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
  </dependencies>
#+end_src

hello/SampleController.java

#+begin_src java
package hello;

import org.springframework.boot.*;
import org.springframework.boot.autoconfigure.*;
import org.springframework.stereotype.*;
import org.springframework.web.bind.annotation.*;

@Controller
@EnableAutoConfiguration
public class SampleController {

    @RequestMapping("/")
    @ResponseBody
    String home() {
    return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        SpringApplication.run(SampleController.class, args);
    }
}
#+end_src

运行

#+begin_src sh
# 运行失败，需要增加两个插件.
java -cp target/my-app-1.0-SNAPSHOT.jar com.mycompany.app.SampleController

# 详细过程参见：
# 2016-06-29-java.org/Maven: 打包可运行的jar包(java application)及依赖项处理
#+end_src

[[http://start.spring.io/][项目生成器]]


3. 运行

此时在浏览器输入http://localhost:8080/，你会看到helloworld字样，这是一个web应用，使用了嵌入式的tomcat。
在pom配置中我们仅仅使用了spring-boot-starter-web依赖，spring boot会根据此依赖下载相关jar包并初始化基本的运行环境，比如说绑定端口8080等。
spring boot封装所有配置信息为键值类型，你想改变默认配置，只需要向应用传入这个键值对就可以，比如我们想改变绑定端口为8081，那么你在main方法里传入“—server.port=8081”即可，或者干脆使用：

#+begin_src java

// 详细过程参见：
// 2016-06-29-java.org/Maven: 打包可运行的jar包(java application)及依赖项处理
// 将依赖库拷贝到lib
mvn dependency:copy-dependencies -DoutputDirectory=target/lib

// 运行
java -cp target/lib/  -jar target/my-app-1.0-SNAPSHOT.jar


// 或者
SpringApplication.run(SampleController.class, "--server.port=8081");
#+end_src

其他插件
Spring boot提供的一些开箱即用的应用非常容易使用，比如监控，你只需要在pom文件中引入：

#+begin_src xml
  <dependency>
   <groupId>org.springframework.boot</groupId>
   <artifactId>spring-boot-starter-actuator</artifactId>
  </dependency>
#+end_src


引入之后，spring boot是默认开启监控的，运行应用你可以在浏览器中输入：

http://localhost:8080/health

就可以看到默认的监控信息了：

#+begin_src js
{"status":"UP","diskSpace":{"status":"UP","total":161067397120,"free":91618398208,"threshold":10485760}}
#+end_src


信息包括程序执行状态以及基本的磁盘信息。
项目例子：https://github.com/indie21/springboot-demo

* 7天学会spring cloud

http://www.cnblogs.com/skyblog/p/5127712.html

** DONE spring cloud教程之使用spring boot创建一个应用
　

