#+SETUPFILE: ../css/level-1.orgcss
#+TITLE: Fluentd

安装 http://docs.fluentd.org/articles/install-by-dmg

sudo launchctl load /Library/LaunchDaemons/td-agent.plist
less /var/log/td-agent/td-agent.log
sudo launchctl unload /Library/LaunchDaemons/td-agent.plist
/etc/td-agent/td-agent.conf



fluent-gem install fluent-plugin-mongo.

$ fluentd --setup ./fluent
$

fluentd -c ./fluent/fluent.conf -vv  --daemon  ./fluent/fluent.pid  -o  ./fluent/fluent.log

fluentd -c ./fluent/fluent.conf -vv

$ echo '{"json":"message"}' | fluent-cat debug.test


curl -X POST -d 'json={"action":"login","user":2}' http://localhost:8888/test.tag.here;

curl -X POST -d 'json={"action":"login","user":2}' http://localhost:8888/typed.x1



When you launch Fluentd, it creates two processes: supervisor and worker. The supervisor process controls the life cycle of the worker process. Please make sure to send any signals to the supervisor process.

Signals

SIGINT or SIGTERM

Stops the daemon gracefully. Fluentd will try to flush the entire memory buffer at once, but will not retry if the flush fails. Fluentd will not flush the file buffer; the logs are persisted on the disk by default.

SIGUSR1

Forces the buffered messages to be flushed and reopens Fluentd’s log. Fluentd will try to flush the current buffer (both memory and file) immediately, and keep flushing at flush_interval.

SIGHUP

Reloads the configuration file by gracefully restarting the worker process. Fluentd will try to flush the entire memory buffer at once, but will not retry if the flush fails. Fluentd will not flush the file buffer; the logs are persisted on the disk by default.

SIGCONT
