* 主要功能介绍
[[http://www.cnblogs.com/sharpxiajun/archive/2013/06/02/3113923.html][参考文章1 ]]
[[http://www.ibm.com/developerworks/cn/data/library/bd-zookeeper/][ZooKeeper 基础知识、部署和应用程序-IBM]]

** 统一命名服务

名称服务是将一个名称映射到与该名称有关联的一些信息的服务。

** 分布式锁服务

*** 锁定 
为了允许在分布式系统中对共享资源进行有序的访问，可能需要实现分布式互斥（distributed mutexes）。ZooKeeper 提供一种简单的方式来实现它们

*** 同步
与互斥同时出现的是同步访问共享资源的需求。无论是实现一个生产者-消费者队列，还是实现一个障碍，ZooKeeper 都提供一个简单的接口来实现该操作。您可以在 Apache ZooKeeper 维基上查看示例，了解如何做到这一点（参阅 参考资料）。


** 配置管理

将集群的配置文件拷贝到zookeeper的文件系统的某个节点上，然后用zookeeper监控所有分布式系统里配置文件的状态，一旦发现有配置文件发生了变化，每台服务器都会收到zookeeper的通知，让每台服务器同步zookeeper里的配置文件，zookeeper服务也会保证同步操作原子性，确保每个服务器的配置文件都能被正确的更新。

** 领导选举

布式系统可能必须处理节点停机的问题，您可能想实现一个自动故障转移策略。ZooKeeper 通过领导者选举对此提供现成的支持。
* 基本使用

** 设置并部署 ZooKeeper 集合体

1.下载并解压:http://zookeeper.apache.org/releases.html

#+begin_src sh
wget http://ftp.jaist.ac.jp/pub/apache/zookeeper/zookeeper-3.4.8/zookeeper-3.4.8.tar.gz
#+end_src

2.创建一个目录，用它来存储与 ZooKeeper 服务器有关联的一些状态：mkdir /var/lib/zookeeper。您可能需要将这个目录创建为根目录，并在以后将这个目录的所有者更改为您希望运行 ZooKeeper 服务器的用户。

#+begin_src sh
mkdir /var/lib/zookeeper
#+end_src

3.设置配置。创建或编辑 zookeeper3.4.5/conf/zoo.cfg 文件
#+begin_src sh
tickTime=2000
dataDir=/var/lib/zookeeper clientPort=2181
initLimit=5 syncLimit=2
server.1=zkserver1.mybiz.com:2888:3888
server.2=zkserver2.mybiz.com:2888:3888
server.3=zkserver3.mybiz.com:2888:3888

server.1=localhost:2888:3888
#+end_src


4. 现在，您已经做好了在每台机器上启动 ZooKeeper 服务器的准备。 启动 ZooKeeper 服务器

#+begin_src sh
zookeeper3.4.5/bin/zkServer.sh start
#+end_src

现在，您可以从其中一台正在运行 ZooKeeper 服务器的机器上启动一个 CLI 客户端。
清单 5. 启动 CLI 客户端
zookeeper3.4.5/ bin/zkCli.sh server
zkserver1.mybiz.com:2181,zkserver2.mybiz.com:2181,zkserver3.mybiz.com:2181




