#+SETUPFILE: ../css/level-1.orgcss
#+TITLE: 分类


* RPG-角色扮演游戏

** Roguelike

[[http://baike.baidu.com/link?url=M95DHrAd7Z2fbw61jVIgaAvtd1AWT9fzZoSIM7BQWg0rLlslAVPtuyfH2kLnTmymbwV1l-NOgyCtspgiOSu7vq][百科]]

其类型始祖游戏Rogue在2009年被游戏权威杂志“PC WORLD”评为“史上最伟大的十个游戏之一”！

*** 特点

+ 生成随机性。每一次新开局游戏都会随机生成游戏场景，敌人，宝物等不同事物。[5]  而玩家的每一次冒险历程也都将是独一无二，不可复制的。更有甚者，只要玩家愿意的话，可以让玩家连扮演的角色都设置成随机生成的。例如敌人，武器，甚至只是一个角色的皮肤或者场景中的河流等。
+ 进程单向性。当你在玩一款Roguelike游戏时，存档功能的唯一作用就是记录你当前的游戏进度，每当存档被读取时，对应的进度就会被清空，直到你进行下一次存档。这种存档机制确保玩家无法利用"S/L大法"来降低游戏难度。更甚至在Roguelike玩家圈中，手动备份存档会被当做一种作弊行为受到鄙视。
+ 不可挽回性。在大多数Roguelike游戏中，每一个角色只有一次生命，一个角色的死亡意味着玩家将永远失去该角色。无论你是主角，敌人，物品或者场景。甚至在很多Roguelike玩家眼中，Roguelike的最大魅力之一就在于体验每一次不同的死亡与失败，并最大努力的做好当下的自己。
+ 游戏非线性。严谨而不失灵活性的游戏规则，使Roguelike具备了极高的自由度，在游戏中，玩家可以发挥想象力，利用各种手段去达成任何他们想做的事情，或合乎常理，或匪夷所思，目的只在于解决他们在游戏中遇到的问题。
+ 画面朴素性。其实Roguelike类游戏的鼻祖Rogue被普遍认为是最先有图形界面的冒险游戏之一，虽然这种“图形界面”抽象的过分。但是很多Roguelike类游戏出于对Rogue的致敬，会直接使用ASCII字符来表示游戏画面，更导致很多游戏的主角都叫同一个名字——@。
+ 系统复杂性。Rogue本身的复杂程度就远远超过同时期的任何一款作品。而Roguelike类游戏可能会在一款游戏中包括多到无法估量的元素，例如地质、气候和生物分布，以及精细到皮肤、肌肉、血液、骨骼和脂肪的战斗系统，甚至战损痊愈后会留下伤疤以及后遗症。在有些游戏里则可能包括数百种的死亡原因，数千种的生物，数万种的物品。可以说除了Roguelike类游戏，再也没有任何传统游戏能够不计成本的拥有如此多的元素了。

*** 例子

贪婪洞窟

* SLG
