* 2015-04： 学习Cocos2d的引擎使用，同时寻找游戏点子和美术

树的种类 ->
真菌树
防御树

* GIS Game

人生魔法 http://jingyan.baidu.com/article/1709ad80dc59cd4634c4f082.html

* demo 

** 英雄纹章

是一款消除战斗类型的游戏。融合了传统三消的玩法，通过消除不同阵型的纹章，让角色发动专属技能，击败前方的敌人。
虽然是老套的勇者拯救公主的剧情，但配合着精心设计的剧本笔者居然在玩的时候开始期待下一步剧情，游戏类型虽属于传统的三消战斗，但在无氪金的环境下一切都显得那么实在，运气、技术缺一不可，完美重现了三消游戏的魅力所在，这款游戏在通关之后笔者一直舍不得把它删掉，在这里也推荐给还没玩过的各位。

** 崩溃大陆(Crashlands)

《崩溃大陆(Crashlands)》是一款结合物品制作、探索与战斗等元素的生存游戏，玩家操控的主角将必须在未知的星球上采集各种资源，打造装备与武器，尽一切力量设法生存下去。

没给这款游戏5星其实很大的原因是为了显得笔者对游戏的要求之高，但这款游戏真的特别棒，“似饥荒而非饥荒”这是众多小伙伴一起给这款游戏的评价，而对于游戏汉化的问题，唯一没“扑街”的游乐园已经放出测试版下载，那些想玩却有语言困难的英语苦手们可以前去体验。

* 三消RPG

《Flyff Puzmon》：此游戏是以Gala Lab开发的PC游戏《Flyff Online》为题材制作而成的三消RPG手游。游戏内的角色可以组队，通过消除同样颜色的珠子来进行攻击，攻破每一个关卡的怪物。通关后可以获得积分点，用积分可以购买角色以及对角色进行合成、强化等。http://news.d.cn/news/view-6992.html

《地牢之心》：Dungeon Hearts是一款益智与RPG相结合的游戏。在游戏中的屏幕下方有四排不断滚动的彩色圆点，四种颜色分别对应队伍中的四个角色，而你要做的就是用手指拖动屏幕下方的彩色圆点进行快速配对消除，一点消除成功队伍中的角色就会发动攻击。 http://play.163.com/12/0525/15/82C2MLP500314OSE.html

《夺宝大作战》： http://news.shouyou.com/news/11202014/151824622.shtml

《战神的挑战》： http://baike.baidu.com/link?url=d059O59grdm9cc9tv3W1Op4T7CC8EgAqAJsQozyE8eyDFQpdY6t8gCY7qUK_Bo9cRS2l6rrCV1bHKW7mEhLWu6T9DQTz8JOM6JTrMX6lp3K

《符文陨落》：作为最古老的游戏类型之一，三消游戏也面临着巨大的挑战，以往那种纯粹的消除玩法已经无法满足玩家越来越挑剔的胃口。所以现在新出的三消游戏都会结合一些其他的玩法，Backflip Studios近期上架的这款游戏就将简单的三消玩法再加入RPG元素，画面的效果相当的不错，下面我们就一起来看看。 http://news.tongbu.com/75825.html

英雄纹章

* Slg游戏

老厂游戏，需要巨大推广费用，整体制作耗时耗钱.

* 塔防游戏

适合手机游戏，游戏性强，大量独立游戏制作，市场偏饱和.

* RogueLike游戏

** RogueLike游戏杂谈: http://news.52pk.com/zt/yxzs008/

Roguelike这种游戏类型在大多数国人看来完全不知为何物，还以为是个刚出炉的新鲜玩意，其实这种游戏来头可大了。
它源自一款名为《Rogue》的迷宫探索类游戏，最早由软件工程师迈克尔托依和格伦韦科曼在上世纪八十年代开发，被普遍认为是最先有图形界面的冒险游戏之一。游戏采用的是ASCII字符界面，内容都是随机生成的，一个@字符就代表玩家自己，虽然看似简单，但实际上游戏要素极为丰富，也颇有挑战性，玩家可以下达多重指令来在随机迷宫中探险，在当年可以说是开创性的，自然是非常受欢迎。因此后来《Rogue》出现了许多模仿者，大批类Rougue游戏陆续诞生，就被统称为Roguelike游戏了。
由于《Rougue》本身是基于早期西方“龙与地下城（DND）”桌面战棋玩法制作而成的游戏，遵循角色扮演游戏规则，所以Roguelike游戏也基本符合DND法则，并隶属于RPG大类。后来，随着Roguelike游戏的不断发展壮大，这种元素丰富、可玩性强的游戏越来越多。国际Roguelike游戏发展会议2008年专门定义了该类型游戏，总结出该类游戏“生成随机性”、“进程单向性”、“不可挽回性”、“游戏非线性”、“画面朴素性”以及“系统复杂性”几大特点，称为“柏林诠释”。看到这里，可能有人会认为，这是一个小众的不为人知的游戏类型，可如果这么想那就大错特错了。相反的，Roguelike可以算得上是历史最悠久范围最广的游戏类型了，甚至许多玩家耳熟能详的游戏大作都或多或少的借鉴了Roguelike的元素，包括《我的世界》、《暗黑破坏神》、《侠盗猎车手》、《上古卷轴》等等，怎么样，是不是瞬间觉得高大上了许多？

** 成功例子

符石守护者;steam;36Y.
贪婪洞窟
饥荒 

游戏性很强

* Rpg
* SolarMax


** V1

1. 一个玩家无法操作太多的星球.  
-> 也许更好，玩家会受到自己可以控制的星球数量限制，避免一个玩家太强.
-> 玩家被击败的时候可以直接随机复活(如果找不到空白星球则无法直接复活)
-> 地图为圆形，最外圈为复活圈，玩家进入展出后该外圈点为空白点，可用于其他玩家加入或复活.

2.进入的新玩家和老玩家差距太多.
-> 由第1点限制不会那么明显.
-> 每一局20分钟，玩家可以玩，但是不会成为头名，但是有各种奖励或者其他收获.

3.每个星球只能全部出动
-> 取消掉按100%移动的策略..
-> 多人游戏的情况下该策略作用不明显.

4.超过N个星球的拥有者会在小地图地图上显示.
-> 黑暗森林，可以直播出比较强的玩家，让大家打他.
-> 领土争夺，

5.每一轮完成后按占领星球数量排名.

** V2

1. 每个人初始化一个星球，10点兵力，每个人最多同时拥有3个星球.
2. 每次移动兵力100%全移动.
3. 当玩家没有任何的兵力判定为死亡。

   ++每个自由星球初始化时有5点兵力，每10s补齐5点兵力，玩家可以占领后战斗后占领星球，该星球产生的兵力归玩家++


2.自由星球最多3点兵力，吃掉后兵力增长.
3.玩家相互吞噬，吞噬玩家N点兵兵力将增加N点兵力，对方玩家失掉星球并减少兵力.


** V3

1.星球

不同单位产出的星球, 5s产出 5，10，15 兵力 星球大小不同.
玩家驻扎星球后获得其兵力产出，并占领星球.
占领星球不驻扎则没有产出，但是会计算为玩家占领的星球数.
占领自由星球将一次性获得其累计产出，不战斗.



* 收入付费

独立游戏如何通过广告赚钱？http://zhuanlan.zhihu.com/p/20441095
你还在凭感觉做游戏吗？谈谈独立游戏如何做市场调研 http://www.indieace.com/topic/485
